source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target ’百思不得姐’ do
pod 'pop'
pod 'DACircularProgress'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'DOUAudioStreamer'
pod 'NJKWebViewProgress'

end
